services:
  - type: web
    name: vulnscanner
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vulnscanner.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DATABASE_URL
        sync: false


